Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -227,22 +227,21 @@ jobs:
           tags: sharuelement/checkoutservice:latest
           context: ./src/checkoutservice/
 
-  nodejs-build:
-  runs-on: ubuntu-latest
-  needs: lint
-  steps:
-    - uses: actions/checkout@v4
-    - name: Use Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '20.x'
-    - name: Install dependencies
-      run: npm ci || { echo "npm ci failed"; exit 1; }
-    - name: Build project
-      run: npm run build --if-present
-    - name: Run tests
-      run: |
-        npm test
-        npm run inside
-        cd ./src/cartservice/src/ && npm test
-
+    nodejs-build:
+    runs-on: ubuntu-latest
+    needs: lint
+    steps:
+      - uses: actions/checkout@v4
+      - name: Use Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20.x'
+      - name: Install dependencies
+        run: npm ci || { echo "npm ci failed"; exit 1; }
+      - name: Build project
+        run: npm run build --if-present
+      - name: Run tests
+        run: |
+          npm test
+          npm run inside
+          cd ./src/cartservice/src/ && npm test
