Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -73,10 +73,15 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
       - name: Print working directory
         run: pwd
       - name: List files
         run: ls -al
+      - name: Check Gradle Wrapper Existence
+        run: |
+          if [ ! -f ./gradlew ]; then echo "gradlew not found!" && exit 1; fi
       - name: Make Gradle Wrapper Executable
         run: chmod +x ./gradlew || true
       - name: Set up JDK 17
@@ -88,7 +93,7 @@ jobs:
         uses: gradle/actions/setup-gradle@v4
       - name: Run Gradle Tests
         run: ./gradlew test
-        
+
   docker-build-and-push-adservice:
     runs-on: ubuntu-latest
     needs: gradle-test
